# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

import noise_dosimeter_pb2 as noise__dosimeter__pb2

GRPC_GENERATED_VERSION = '1.73.1'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + f' but the generated code in noise_dosimeter_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class NoiseDosimeterStub(object):
    """The service definition for the NoisePro Dosimeter.
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.UploadNoiseData = channel.unary_unary(
                '/noisedosimeter.NoiseDosimeter/UploadNoiseData',
                request_serializer=noise__dosimeter__pb2.NoiseDataRequest.SerializeToString,
                response_deserializer=noise__dosimeter__pb2.NoiseDataResponse.FromString,
                _registered_method=True)


class NoiseDosimeterServicer(object):
    """The service definition for the NoisePro Dosimeter.
    """

    def UploadNoiseData(self, request, context):
        """Sends noise data from a dosimeter.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_NoiseDosimeterServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'UploadNoiseData': grpc.unary_unary_rpc_method_handler(
                    servicer.UploadNoiseData,
                    request_deserializer=noise__dosimeter__pb2.NoiseDataRequest.FromString,
                    response_serializer=noise__dosimeter__pb2.NoiseDataResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'noisedosimeter.NoiseDosimeter', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('noisedosimeter.NoiseDosimeter', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class NoiseDosimeter(object):
    """The service definition for the NoisePro Dosimeter.
    """

    @staticmethod
    def UploadNoiseData(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/noisedosimeter.NoiseDosimeter/UploadNoiseData',
            noise__dosimeter__pb2.NoiseDataRequest.SerializeToString,
            noise__dosimeter__pb2.NoiseDataResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
